version: '2'

services:  

  ti-dhome-ui:
    image: kalemena/ti-dhome-ui
    build: .
    restart: always
    ports:
     - "9090:8080"
    volumes:
# Edit mode - changes in files are in sync live with redenring on browser
     - ./src/ti-dhome/src:/opt/ti-dhome/src
     - ./src/ti-dhome/static:/opt/ti-dhome/static